fix compilation error when using language verion 14
I was trying to compile the project then ran into this, because it's using "latest" langversion.

error CS9273: In language version 14.0, 'field' is a keyword within a property accessor. Rename the variable or use the identifier '@field' instead.